### ISSUE TITLE
Links for email addresses & zoom invites

### ISSUE THREAD

**Issue by 17isgreaterthan18** [pybash/genbruins#1]
turn emails and zoom invites into links. Use mailto: for email addresses.

**Comment by pybash** [comment]
Thanks for the notice, I have now added hyperlinks with an animated underline. https://github.com/pybash/genbruins/commit/4efa037554920795c9f5f26722f736e752f059ec
I do want to note that the zoom invite link in the Contact Us page directs to Google's main site, and the email link now uses the mailto: protocol but genbruins@bhs.com is not a valid email address.
